FROM python:alpine3.7

ARG GROUP_ID
ARG USER_ID

RUN apk update \
  && apk add --no-cache --update make python3-dev  gcc build-base \
  && rm -rf /var/cache/apk/*

RUN pip3 install --upgrade pip \
  && pip3 install \
    coverage \
    pycodestyle \
    pylint \
    wheel

WORKDIR /usr/src/app

COPY requirements.txt requirements-dev.txt /tmp/

RUN pip3 install -r /tmp/requirements-dev.txt \
  && rm -f /tmp/requirements-dev.txt \
  && rm -f /tmp/requirements.txt

RUN addgroup -g ${GROUP_ID} builder \
  && adduser -h /usr/src/app -G builder -D -H -u ${USER_ID} builder
