FROM python:alpine3.7

RUN apk update \
  && apk add -u make \
  && rm -rf /var/cache/apk/*

RUN pip3 install --upgrade pip \
  && pip3 install \
    coverage \
    pycodestyle \
    pylint \
    wheel

WORKDIR /usr/src/app

COPY requirements.txt requirements-dev.txt /tmp/

RUN pip3 install -r /tmp/requirements-dev.txt \
  && rm -f /tmp/requirements-dev.txt \
  && rm -f /tmp/requirements.txt
